[2025-06-25T08:37:04.447+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-25T08:37:04.780+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TEST_step2_slurm_20250625T083108.submit_slurm manual__2025-06-25T08:34:35.851100+00:00 [queued]>
[2025-06-25T08:37:04.790+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TEST_step2_slurm_20250625T083108.submit_slurm manual__2025-06-25T08:34:35.851100+00:00 [queued]>
[2025-06-25T08:37:04.790+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-25T08:37:04.821+0000] {taskinstance.py:2890} INFO - Executing <Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> on 2025-06-25 08:34:35.851100+00:00
[2025-06-25T08:37:04.835+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'TEST_step2_slurm_20250625T083108', 'submit_slurm', 'manual__2025-06-25T08:34:35.851100+00:00', '--job-id', '379', '--raw', '--subdir', 'DAGS_FOLDER/TEST_step2_slurm_20250625T083108.py', '--cfg-path', '/tmp/tmpimpkk7ko']
[2025-06-25T08:37:04.838+0000] {standard_task_runner.py:105} INFO - Job 379: Subtask submit_slurm
[2025-06-25T08:37:04.851+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=509) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-25T08:37:04.854+0000] {standard_task_runner.py:72} INFO - Started process 520 to run task
[2025-06-25T08:37:04.954+0000] {task_command.py:467} INFO - Running <TaskInstance: TEST_step2_slurm_20250625T083108.submit_slurm manual__2025-06-25T08:34:35.851100+00:00 [running]> on host 1cabd79ac10f
[2025-06-25T08:37:05.134+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='TEST_step2_slurm_20250625T083108' AIRFLOW_CTX_TASK_ID='submit_slurm' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T08:34:35.851100+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T08:34:35.851100+00:00'
[2025-06-25T08:37:05.137+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-25T08:37:05.138+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-25T08:37:05.138+0000] {logging_mixin.py:190} INFO - Current task name:submit_slurm state:running start_date:2025-06-25 08:37:04.781694+00:00
[2025-06-25T08:37:05.139+0000] {logging_mixin.py:190} INFO - Dag name:TEST_step2_slurm_20250625T083108 and current dag run status:running
[2025-06-25T08:37:05.139+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-25T08:37:05.155+0000] {base.py:84} INFO - Retrieving connection 'hpc_ssh'
[2025-06-25T08:37:05.160+0000] {ssh.py:286} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-06-25T08:37:05.222+0000] {transport.py:1944} INFO - Connected (version 2.0, client OpenSSH_8.0)
[2025-06-25T08:37:05.833+0000] {transport.py:1944} INFO - Authentication (password) successful!
[2025-06-25T08:37:07.548+0000] {slurm_operator.py:19} INFO - sbatch output: 
[2025-06-25T08:37:07.558+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/slurm_operator.py", line 20, in execute
    job_id = output.strip().split()[-1]
             ~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
[2025-06-25T08:37:07.765+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-25T08:37:07.789+0000] {logging_mixin.py:190} INFO - Task start:2025-06-25 08:37:04.781694+00:00 end:2025-06-25 08:37:07.761511+00:00 duration:2.979817
[2025-06-25T08:37:07.802+0000] {logging_mixin.py:190} INFO - Task:<Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> dag:<DAG: TEST_step2_slurm_20250625T083108> dagrun:<DagRun TEST_step2_slurm_20250625T083108 @ 2025-06-25 08:34:35.851100+00:00: manual__2025-06-25T08:34:35.851100+00:00, state:running, queued_at: 2025-06-25 08:34:35.883151+00:00. externally triggered: True>
[2025-06-25T08:37:07.807+0000] {logging_mixin.py:190} INFO - Failure caused by list index out of range
[2025-06-25T08:37:07.808+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=TEST_step2_slurm_20250625T083108, task_id=submit_slurm, run_id=manual__2025-06-25T08:34:35.851100+00:00, execution_date=20250625T083435, start_date=20250625T083704, end_date=20250625T083707
[2025-06-25T08:37:08.952+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-25T08:37:08.968+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 379 for task submit_slurm (list index out of range; 520)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/slurm_operator.py", line 20, in execute
    job_id = output.strip().split()[-1]
             ~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
[2025-06-25T08:37:09.046+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-25T08:37:09.270+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-25T08:37:09.293+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
