[2025-06-09T09:17:13.897+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-09T09:17:13.915+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-06-09T09:17:11.159954+00:00 [queued]>
[2025-06-09T09:17:13.925+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-06-09T09:17:11.159954+00:00 [queued]>
[2025-06-09T09:17:13.925+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-09T09:17:13.943+0000] {taskinstance.py:2890} INFO - Executing <Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> on 2025-06-09 09:17:11.159954+00:00
[2025-06-09T09:17:13.952+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-09T09:17:13.954+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2025-06-09T09:17:13.955+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'slurm_async_job', 'submit_slurm', 'manual__2025-06-09T09:17:11.159954+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/slurm_test_job.py', '--cfg-path', '/tmp/tmpgj7r3igx']
[2025-06-09T09:17:13.957+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask submit_slurm
[2025-06-09T09:17:14.007+0000] {task_command.py:467} INFO - Running <TaskInstance: slurm_async_job.submit_slurm manual__2025-06-09T09:17:11.159954+00:00 [running]> on host 9406efa7f156
[2025-06-09T09:17:14.090+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='slurm_async_job' AIRFLOW_CTX_TASK_ID='submit_slurm' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T09:17:11.159954+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T09:17:11.159954+00:00'
[2025-06-09T09:17:14.092+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-09T09:17:14.093+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-09T09:17:14.093+0000] {logging_mixin.py:190} INFO - Current task name:submit_slurm state:running start_date:2025-06-09 09:17:13.916178+00:00
[2025-06-09T09:17:14.094+0000] {logging_mixin.py:190} INFO - Dag name:slurm_async_job and current dag run status:running
[2025-06-09T09:17:14.094+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-09T09:17:14.106+0000] {base.py:84} INFO - Retrieving connection 'hpc_ssh'
[2025-06-09T09:17:14.107+0000] {ssh.py:286} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-06-09T09:17:14.167+0000] {transport.py:1944} INFO - Connected (version 2.0, client OpenSSH_8.0)
[2025-06-09T09:17:14.777+0000] {transport.py:1944} INFO - Authentication (password) successful!
[2025-06-09T09:17:17.113+0000] {slurm_operator.py:19} INFO - sbatch output: Submitted batch job 16983

[2025-06-09T09:17:17.114+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-06-09T09:17:17.134+0000] {taskinstance.py:289} INFO - Pausing task as DEFERRED. dag_id=slurm_async_job, task_id=submit_slurm, run_id=manual__2025-06-09T09:17:11.159954+00:00, execution_date=20250609T091711, start_date=20250609T091713
[2025-06-09T09:17:17.135+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-09T09:17:17.172+0000] {local_task_job_runner.py:260} INFO - Task exited with return code 100 (task deferral)
[2025-06-09T09:17:17.172+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-06-09T09:17:23.252+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-09T09:17:23.270+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-06-09T09:17:11.159954+00:00 [queued]>
[2025-06-09T09:17:23.279+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-06-09T09:17:11.159954+00:00 [queued]>
[2025-06-09T09:17:23.280+0000] {taskinstance.py:2865} INFO - Resuming after deferral
[2025-06-09T09:17:23.295+0000] {taskinstance.py:2890} INFO - Executing <Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> on 2025-06-09 09:17:11.159954+00:00
[2025-06-09T09:17:23.303+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=109) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-09T09:17:23.305+0000] {standard_task_runner.py:72} INFO - Started process 111 to run task
[2025-06-09T09:17:23.305+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'slurm_async_job', 'submit_slurm', 'manual__2025-06-09T09:17:11.159954+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/slurm_test_job.py', '--cfg-path', '/tmp/tmpyy709b5z']
[2025-06-09T09:17:23.307+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask submit_slurm
[2025-06-09T09:17:23.360+0000] {task_command.py:467} INFO - Running <TaskInstance: slurm_async_job.submit_slurm manual__2025-06-09T09:17:11.159954+00:00 [running]> on host 9406efa7f156
[2025-06-09T09:17:23.427+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-09T09:17:23.428+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-09T09:17:23.428+0000] {logging_mixin.py:190} INFO - Current task name:submit_slurm state:running start_date:2025-06-09 09:17:13.916178+00:00
[2025-06-09T09:17:23.429+0000] {logging_mixin.py:190} INFO - Dag name:slurm_async_job and current dag run status:running
[2025-06-09T09:17:23.429+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-09T09:17:23.430+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1816, in resume_execution
    return execute_callable(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/slurm_operator.py", line 31, in execute_complete
    raise Exception(f"SLURM job failed: {event.get('message', 'Unknown error')}")
Exception: SLURM job failed: Unknown error
[2025-06-09T09:17:23.441+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-09T09:17:23.441+0000] {logging_mixin.py:190} INFO - Task start:2025-06-09 09:17:13.916178+00:00 end:2025-06-09 09:17:23.440746+00:00 duration:9.524568
[2025-06-09T09:17:23.442+0000] {logging_mixin.py:190} INFO - Task:<Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> dag:<DAG: slurm_async_job> dagrun:<DagRun slurm_async_job @ 2025-06-09 09:17:11.159954+00:00: manual__2025-06-09T09:17:11.159954+00:00, state:running, queued_at: 2025-06-09 09:17:11.175635+00:00. externally triggered: True>
[2025-06-09T09:17:23.442+0000] {logging_mixin.py:190} INFO - Failure caused by SLURM job failed: Unknown error
[2025-06-09T09:17:23.443+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=slurm_async_job, task_id=submit_slurm, run_id=manual__2025-06-09T09:17:11.159954+00:00, execution_date=20250609T091711, start_date=20250609T091713, end_date=20250609T091723
[2025-06-09T09:17:23.468+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-09T09:17:23.469+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 90 for task submit_slurm (SLURM job failed: Unknown error; 111)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1816, in resume_execution
    return execute_callable(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/slurm_operator.py", line 31, in execute_complete
    raise Exception(f"SLURM job failed: {event.get('message', 'Unknown error')}")
Exception: SLURM job failed: Unknown error
[2025-06-09T09:17:23.486+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-09T09:17:23.503+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T09:17:23.505+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
