[2025-04-09T10:31:57.477+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T10:31:57.496+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-04-09T10:31:53.725540+00:00 [queued]>
[2025-04-09T10:31:57.506+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-04-09T10:31:53.725540+00:00 [queued]>
[2025-04-09T10:31:57.507+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-09T10:31:57.521+0000] {taskinstance.py:2890} INFO - Executing <Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> on 2025-04-09 10:31:53.725540+00:00
[2025-04-09T10:31:57.529+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=669) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T10:31:57.532+0000] {standard_task_runner.py:72} INFO - Started process 671 to run task
[2025-04-09T10:31:57.531+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'slurm_async_job', 'submit_slurm', 'manual__2025-04-09T10:31:53.725540+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/slurm_test_job.py', '--cfg-path', '/tmp/tmpi6lx7vah']
[2025-04-09T10:31:57.532+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask submit_slurm
[2025-04-09T10:31:57.586+0000] {task_command.py:467} INFO - Running <TaskInstance: slurm_async_job.submit_slurm manual__2025-04-09T10:31:53.725540+00:00 [running]> on host 3f0a98f0bd17
[2025-04-09T10:31:57.703+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='slurm_async_job' AIRFLOW_CTX_TASK_ID='submit_slurm' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T10:31:53.725540+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T10:31:53.725540+00:00'
[2025-04-09T10:31:57.705+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T10:31:57.706+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T10:31:57.707+0000] {logging_mixin.py:190} INFO - Current task name:submit_slurm state:running start_date:2025-04-09 10:31:57.497288+00:00
[2025-04-09T10:31:57.709+0000] {logging_mixin.py:190} INFO - Dag name:slurm_async_job and current dag run status:running
[2025-04-09T10:31:57.710+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T10:31:57.724+0000] {base.py:84} INFO - Retrieving connection 'hpc_ssh'
[2025-04-09T10:31:57.727+0000] {ssh.py:286} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-04-09T10:31:57.788+0000] {transport.py:1944} INFO - Connected (version 2.0, client OpenSSH_8.0)
[2025-04-09T10:31:58.153+0000] {transport.py:1944} INFO - Authentication (password) successful!
[2025-04-09T10:32:04.852+0000] {slurm_operator.py:18} INFO - sbatch output: Submitted batch job 6689

[2025-04-09T10:32:04.857+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-04-09T10:32:04.912+0000] {taskinstance.py:289} INFO - Pausing task as DEFERRED. dag_id=slurm_async_job, task_id=submit_slurm, run_id=manual__2025-04-09T10:31:53.725540+00:00, execution_date=20250409T103153, start_date=20250409T103157
[2025-04-09T10:32:04.913+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T10:32:04.963+0000] {local_task_job_runner.py:260} INFO - Task exited with return code 100 (task deferral)
[2025-04-09T10:32:04.964+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-09T10:32:08.249+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T10:32:08.269+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-04-09T10:31:53.725540+00:00 [queued]>
[2025-04-09T10:32:08.278+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-04-09T10:31:53.725540+00:00 [queued]>
[2025-04-09T10:32:08.279+0000] {taskinstance.py:2865} INFO - Resuming after deferral
[2025-04-09T10:32:08.295+0000] {taskinstance.py:2890} INFO - Executing <Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> on 2025-04-09 10:31:53.725540+00:00
[2025-04-09T10:32:08.303+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=675) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T10:32:08.305+0000] {standard_task_runner.py:72} INFO - Started process 677 to run task
[2025-04-09T10:32:08.306+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'slurm_async_job', 'submit_slurm', 'manual__2025-04-09T10:31:53.725540+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/slurm_test_job.py', '--cfg-path', '/tmp/tmp8d0beh7o']
[2025-04-09T10:32:08.308+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask submit_slurm
[2025-04-09T10:32:08.359+0000] {task_command.py:467} INFO - Running <TaskInstance: slurm_async_job.submit_slurm manual__2025-04-09T10:31:53.725540+00:00 [running]> on host 3f0a98f0bd17
[2025-04-09T10:32:08.437+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T10:32:08.438+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T10:32:08.439+0000] {logging_mixin.py:190} INFO - Current task name:submit_slurm state:running start_date:2025-04-09 10:31:57.497288+00:00
[2025-04-09T10:32:08.439+0000] {logging_mixin.py:190} INFO - Dag name:slurm_async_job and current dag run status:running
[2025-04-09T10:32:08.440+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T10:32:08.440+0000] {baseoperator.py:1810} ERROR - Trigger failed:
Traceback (most recent call last):

  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/triggerer_job_runner.py", line 698, in update_triggers
    trigger_class = self.get_trigger_by_classpath(new_trigger_orm.classpath)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/triggerer_job_runner.py", line 752, in get_trigger_by_classpath
    self.trigger_cache[classpath] = import_string(classpath)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/***/.local/lib/python3.12/site-packages/***/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1319, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'slurm_plugin.triggers'; 'slurm_plugin' is not a package

[2025-04-09T10:32:08.451+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1811, in resume_execution
    raise TaskDeferralError(next_kwargs.get("error", "Unknown"))
airflow.exceptions.TaskDeferralError: Trigger failure
[2025-04-09T10:32:08.457+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-09T10:32:08.457+0000] {logging_mixin.py:190} INFO - Task start:2025-04-09 10:31:57.497288+00:00 end:2025-04-09 10:32:08.456777+00:00 duration:10.959489
[2025-04-09T10:32:08.458+0000] {logging_mixin.py:190} INFO - Task:<Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> dag:<DAG: slurm_async_job> dagrun:<DagRun slurm_async_job @ 2025-04-09 10:31:53.725540+00:00: manual__2025-04-09T10:31:53.725540+00:00, state:running, queued_at: 2025-04-09 10:31:53.747891+00:00. externally triggered: True>
[2025-04-09T10:32:08.458+0000] {logging_mixin.py:190} INFO - Failure caused by Trigger failure
[2025-04-09T10:32:08.459+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=slurm_async_job, task_id=submit_slurm, run_id=manual__2025-04-09T10:31:53.725540+00:00, execution_date=20250409T103153, start_date=20250409T103157, end_date=20250409T103208
[2025-04-09T10:32:08.489+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T10:32:08.492+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task submit_slurm (Trigger failure; 677)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1811, in resume_execution
    raise TaskDeferralError(next_kwargs.get("error", "Unknown"))
airflow.exceptions.TaskDeferralError: Trigger failure
[2025-04-09T10:32:08.528+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-09T10:32:08.547+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T10:32:08.549+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
