[2025-06-22T11:17:47.501+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-22T11:17:47.508+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_git_only.git_clone manual__2025-06-22T11:17:45.632264+00:00 [queued]>
[2025-06-22T11:17:47.511+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_git_only.git_clone manual__2025-06-22T11:17:45.632264+00:00 [queued]>
[2025-06-22T11:17:47.511+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-22T11:17:47.515+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): git_clone> on 2025-06-22 11:17:45.632264+00:00
[2025-06-22T11:17:47.520+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=298) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-22T11:17:47.521+0000] {standard_task_runner.py:72} INFO - Started process 299 to run task
[2025-06-22T11:17:47.522+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_git_only', 'git_clone', 'manual__2025-06-22T11:17:45.632264+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/test_unai_de_git_step1_git_20250529T085048.py', '--cfg-path', '/tmp/tmpuuxwhzpg']
[2025-06-22T11:17:47.523+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask git_clone
[2025-06-22T11:17:47.674+0000] {task_command.py:467} INFO - Running <TaskInstance: test_git_only.git_clone manual__2025-06-22T11:17:45.632264+00:00 [running]> on host f497868a7383
[2025-06-22T11:17:47.698+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Unai Motriko' AIRFLOW_CTX_DAG_ID='test_git_only' AIRFLOW_CTX_TASK_ID='git_clone' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T11:17:45.632264+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T11:17:45.632264+00:00'
[2025-06-22T11:17:47.698+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-22T11:17:47.699+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-22T11:17:47.699+0000] {logging_mixin.py:190} INFO - Current task name:git_clone state:running start_date:2025-06-22 11:17:47.508932+00:00
[2025-06-22T11:17:47.699+0000] {logging_mixin.py:190} INFO - Dag name:test_git_only and current dag run status:running
[2025-06-22T11:17:47.699+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-22T11:17:47.699+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-06-22T11:17:47.700+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "git clone https://github.com/motri/hello-world "']
[2025-06-22T11:17:47.705+0000] {subprocess.py:99} INFO - Output:
[2025-06-22T11:17:47.706+0000] {subprocess.py:106} INFO - bash: line 1: git: command not found
[2025-06-22T11:17:47.707+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-06-22T11:17:47.711+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-06-22T11:17:47.713+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-22T11:17:47.713+0000] {logging_mixin.py:190} INFO - Task start:2025-06-22 11:17:47.508932+00:00 end:2025-06-22 11:17:47.713417+00:00 duration:0.204485
[2025-06-22T11:17:47.714+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): git_clone> dag:<DAG: test_git_only> dagrun:<DagRun test_git_only @ 2025-06-22 11:17:45.632264+00:00: manual__2025-06-22T11:17:45.632264+00:00, state:running, queued_at: 2025-06-22 11:17:45.640190+00:00. externally triggered: True>
[2025-06-22T11:17:47.714+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-06-22T11:17:47.714+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=test_git_only, task_id=git_clone, run_id=manual__2025-06-22T11:17:45.632264+00:00, execution_date=20250622T111745, start_date=20250622T111747, end_date=20250622T111747
[2025-06-22T11:17:47.723+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-22T11:17:47.723+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task git_clone (Bash command failed. The command returned a non-zero exit code 127.; 299)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-06-22T11:17:47.752+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-22T11:17:47.845+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T11:17:47.846+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
