[2025-06-09T09:15:45.691+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-09T09:15:45.715+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-06-09T09:15:39.509665+00:00 [queued]>
[2025-06-09T09:15:45.725+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-06-09T09:15:39.509665+00:00 [queued]>
[2025-06-09T09:15:45.726+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-09T09:15:45.746+0000] {taskinstance.py:2890} INFO - Executing <Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> on 2025-06-09 09:15:39.509665+00:00
[2025-06-09T09:15:45.757+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-09T09:15:45.759+0000] {standard_task_runner.py:72} INFO - Started process 80 to run task
[2025-06-09T09:15:45.760+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'slurm_async_job', 'submit_slurm', 'manual__2025-06-09T09:15:39.509665+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/slurm_test_job.py', '--cfg-path', '/tmp/tmpf3_2s369']
[2025-06-09T09:15:45.769+0000] {standard_task_runner.py:105} INFO - Job 88: Subtask submit_slurm
[2025-06-09T09:15:45.836+0000] {task_command.py:467} INFO - Running <TaskInstance: slurm_async_job.submit_slurm manual__2025-06-09T09:15:39.509665+00:00 [running]> on host 9406efa7f156
[2025-06-09T09:15:45.943+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='slurm_async_job' AIRFLOW_CTX_TASK_ID='submit_slurm' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T09:15:39.509665+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T09:15:39.509665+00:00'
[2025-06-09T09:15:45.945+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-09T09:15:45.945+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-09T09:15:45.947+0000] {logging_mixin.py:190} INFO - Current task name:submit_slurm state:running start_date:2025-06-09 09:15:45.716317+00:00
[2025-06-09T09:15:45.948+0000] {logging_mixin.py:190} INFO - Dag name:slurm_async_job and current dag run status:running
[2025-06-09T09:15:45.949+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-09T09:15:45.977+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/slurm_operator.py", line 15, in execute
    hook = SSHHook(ssh_conn_id=self.ssh_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/hooks/ssh.py", line 153, in __init__
    conn = self.get_connection(self.ssh_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `hpc_ssh` isn't defined
[2025-06-09T09:15:45.993+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-09T09:15:45.994+0000] {logging_mixin.py:190} INFO - Task start:2025-06-09 09:15:45.716317+00:00 end:2025-06-09 09:15:45.992762+00:00 duration:0.276445
[2025-06-09T09:15:45.996+0000] {logging_mixin.py:190} INFO - Task:<Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> dag:<DAG: slurm_async_job> dagrun:<DagRun slurm_async_job @ 2025-06-09 09:15:39.509665+00:00: manual__2025-06-09T09:15:39.509665+00:00, state:running, queued_at: 2025-06-09 09:15:39.547367+00:00. externally triggered: True>
[2025-06-09T09:15:45.997+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `hpc_ssh` isn't defined
[2025-06-09T09:15:45.999+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=slurm_async_job, task_id=submit_slurm, run_id=manual__2025-06-09T09:15:39.509665+00:00, execution_date=20250609T091539, start_date=20250609T091545, end_date=20250609T091545
[2025-06-09T09:15:46.042+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-09T09:15:46.043+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 88 for task submit_slurm (The conn_id `hpc_ssh` isn't defined; 80)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/slurm_operator.py", line 15, in execute
    hook = SSHHook(ssh_conn_id=self.ssh_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/ssh/hooks/ssh.py", line 153, in __init__
    conn = self.get_connection(self.ssh_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `hpc_ssh` isn't defined
[2025-06-09T09:15:46.072+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-09T09:15:46.096+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T09:15:46.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
