[2025-04-09T09:37:10.974+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T09:37:10.992+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-04-09T09:37:08.152228+00:00 [queued]>
[2025-04-09T09:37:11.000+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: slurm_async_job.submit_slurm manual__2025-04-09T09:37:08.152228+00:00 [queued]>
[2025-04-09T09:37:11.001+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-09T09:37:11.015+0000] {taskinstance.py:2890} INFO - Executing <Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> on 2025-04-09 09:37:08.152228+00:00
[2025-04-09T09:37:11.022+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=463) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T09:37:11.025+0000] {standard_task_runner.py:72} INFO - Started process 465 to run task
[2025-04-09T09:37:11.026+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'slurm_async_job', 'submit_slurm', 'manual__2025-04-09T09:37:08.152228+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/slurm_test_job.py', '--cfg-path', '/tmp/tmp3n2wo8vy']
[2025-04-09T09:37:11.027+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask submit_slurm
[2025-04-09T09:37:11.077+0000] {task_command.py:467} INFO - Running <TaskInstance: slurm_async_job.submit_slurm manual__2025-04-09T09:37:08.152228+00:00 [running]> on host 402b386a0bbc
[2025-04-09T09:37:11.161+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='slurm_async_job' AIRFLOW_CTX_TASK_ID='submit_slurm' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T09:37:08.152228+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T09:37:08.152228+00:00'
[2025-04-09T09:37:11.162+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T09:37:11.163+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T09:37:11.163+0000] {logging_mixin.py:190} INFO - Current task name:submit_slurm state:running start_date:2025-04-09 09:37:10.993120+00:00
[2025-04-09T09:37:11.164+0000] {logging_mixin.py:190} INFO - Dag name:slurm_async_job and current dag run status:running
[2025-04-09T09:37:11.164+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T09:37:11.173+0000] {base.py:84} INFO - Retrieving connection 'hpc_ssh'
[2025-04-09T09:37:11.174+0000] {ssh.py:286} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-04-09T09:37:12.295+0000] {transport.py:1944} INFO - Connected (version 2.0, client OpenSSH_8.0)
[2025-04-09T09:37:12.964+0000] {transport.py:1944} INFO - Authentication (password) successful!
[2025-04-09T09:37:14.770+0000] {slurm_operator.py:18} INFO - sbatch output: 
[2025-04-09T09:37:14.774+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/slurm_operator.py", line 19, in execute
    job_id = output.strip().split()[-1]
             ~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
[2025-04-09T09:37:14.811+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-09T09:37:14.813+0000] {logging_mixin.py:190} INFO - Task start:2025-04-09 09:37:10.993120+00:00 end:2025-04-09 09:37:14.809532+00:00 duration:3.816412
[2025-04-09T09:37:14.815+0000] {logging_mixin.py:190} INFO - Task:<Task(SubmitAndMonitorSlurmJobOperator): submit_slurm> dag:<DAG: slurm_async_job> dagrun:<DagRun slurm_async_job @ 2025-04-09 09:37:08.152228+00:00: manual__2025-04-09T09:37:08.152228+00:00, state:running, queued_at: 2025-04-09 09:37:08.162579+00:00. externally triggered: True>
[2025-04-09T09:37:14.816+0000] {logging_mixin.py:190} INFO - Failure caused by list index out of range
[2025-04-09T09:37:14.818+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=slurm_async_job, task_id=submit_slurm, run_id=manual__2025-04-09T09:37:08.152228+00:00, execution_date=20250409T093708, start_date=20250409T093710, end_date=20250409T093714
[2025-04-09T09:37:14.897+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T09:37:14.899+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task submit_slurm (list index out of range; 465)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/operators/slurm_operator.py", line 19, in execute
    job_id = output.strip().split()[-1]
             ~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
[2025-04-09T09:37:14.937+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-09T09:37:14.978+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T09:37:14.981+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
