[2025-06-19T10:47:13.607+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-19T10:47:13.663+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clone_and_scp.scp_repo_to_remote manual__2025-06-19T10:45:01.222263+00:00 [queued]>
[2025-06-19T10:47:13.678+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clone_and_scp.scp_repo_to_remote manual__2025-06-19T10:45:01.222263+00:00 [queued]>
[2025-06-19T10:47:13.678+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-06-19T10:47:13.695+0000] {taskinstance.py:2890} INFO - Executing <Task(SSHOperator): scp_repo_to_remote> on 2025-06-19 10:45:01.222263+00:00
[2025-06-19T10:47:13.702+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1969) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-19T10:47:13.704+0000] {standard_task_runner.py:72} INFO - Started process 1971 to run task
[2025-06-19T10:47:13.705+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'clone_and_scp', 'scp_repo_to_remote', 'manual__2025-06-19T10:45:01.222263+00:00', '--job-id', '350', '--raw', '--subdir', 'DAGS_FOLDER/clone_scp.py', '--cfg-path', '/tmp/tmpup_d91jp']
[2025-06-19T10:47:13.707+0000] {standard_task_runner.py:105} INFO - Job 350: Subtask scp_repo_to_remote
[2025-06-19T10:47:13.758+0000] {task_command.py:467} INFO - Running <TaskInstance: clone_and_scp.scp_repo_to_remote manual__2025-06-19T10:45:01.222263+00:00 [running]> on host 9406efa7f156
[2025-06-19T10:47:13.821+0000] {abstractoperator.py:783} ERROR - Exception rendering Jinja template for task 'scp_repo_to_remote', field 'command'. Template: '\n    scp -r -o StrictHostKeyChecking=no /tmp/repo {{ conn.my_ssh_connection.login }}@{{ conn.my_ssh_connection.host }}:/home/{{ conn.my_ssh_connection.login }}/\n    '
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 171, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 730, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 127, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 301, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 296, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/sandbox.py", line 319, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py", line 149, in __getattr__
    self.var = Connection.get_connection_from_secrets(key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_ssh_connection` isn't defined
[2025-06-19T10:47:13.837+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 171, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 730, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 127, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 301, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 296, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/sandbox.py", line 319, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py", line 149, in __getattr__
    self.var = Connection.get_connection_from_secrets(key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_ssh_connection` isn't defined
[2025-06-19T10:47:13.846+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-19T10:47:13.846+0000] {logging_mixin.py:190} INFO - Task start:2025-06-19 10:47:13.664474+00:00 end:2025-06-19 10:47:13.845854+00:00 duration:0.18138
[2025-06-19T10:47:13.847+0000] {logging_mixin.py:190} INFO - Task:<Task(SSHOperator): scp_repo_to_remote> dag:<DAG: clone_and_scp> dagrun:<DagRun clone_and_scp @ 2025-06-19 10:45:01.222263+00:00: manual__2025-06-19T10:45:01.222263+00:00, state:running, queued_at: 2025-06-19 10:45:01.236431+00:00. externally triggered: True>
[2025-06-19T10:47:13.847+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `my_ssh_connection` isn't defined
[2025-06-19T10:47:13.848+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=clone_and_scp, task_id=scp_repo_to_remote, run_id=manual__2025-06-19T10:45:01.222263+00:00, execution_date=20250619T104501, start_date=20250619T104713, end_date=20250619T104713
[2025-06-19T10:47:13.879+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-19T10:47:13.880+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 350 for task scp_repo_to_remote (The conn_id `my_ssh_connection` isn't defined; 1971)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3117, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3540, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1442, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 775, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 171, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 730, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 127, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 301, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 296, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/sandbox.py", line 319, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/context.py", line 149, in __getattr__
    self.var = Connection.get_connection_from_secrets(key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_ssh_connection` isn't defined
[2025-06-19T10:47:13.930+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-19T10:47:13.975+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T10:47:13.978+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
